### ISSUE TITLE
Job Stories

### ISSUE THREAD

**Issue by dandevri** [MartijnKeesmaat/dating-app#3]
I don't immediately see which specific Job Story you are going to work on. All of the Job Stories you've written are a bit generic you can focus on filtering results, or starting a conversation and they are very different features. 

Based on the wireframes I'll assume you'll be working on:

> When I am looking for potential relations, I want to be able to filter the results, so I can have an influence on the results I am searching for. For example finding people that live close to me, or people that are close to me in age.

And that is too generic... try to narrow it down.

**Comment by MartijnKeesmaat** [comment]
I've elaborated more on which job story I choose and why on the [wiki page of this week](https://github.com/MartijnKeesmaat/dating-app/wiki/Week-4#project).

**Comment by dandevri** [comment]
👌
